import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.ensemble import RandomForestClassifier


X_train = np.array(["[18][19] Concomitant use of retigabine and digoxin may increase serum concentration of the latter.",
"Thanks for posting this feedback on Neuromonics - it's interesting to get a longer-term perspective on this particular treatment.",
"Have you tried melatonin or something like that for Sleeping.",
"Now, acceptance and not panicking are are both good things and would be part of TRT or CBT.",
"I have completely stopped masking at night now.",
"You can buy a good laser for 1500 Usd.",
"As stated above, I have had 3 sessions of acupuncture but Im not confident about the results.",
"I guess it all depends on your tinnitus level at the point I started taking trobalt.",
"Not sure how it would be any more dangerous than a masking device.",
"I am surprised by the amount of blame Trobalt has been getting.",
"I did TRT and had the noise generators.",
"Anyways, I can keep everyone updated on my experiences with the AM-101 study.",
"Would someone please DM me information about LLLT, such as science articles, associated doctors, best DIY lasers, claimed success stories, common methods of treatment (such as timg vs rest), etc?",
"If you haven't already tried it, I'd suggest giving melatonin (http://en.wikipedia.org/wiki/Melatonin) a shot first.",
"The idea is that if you listen to masking sounds, keep them below your T level, so you can habituate while having something to distract your brain for now.",
"By fighting, it doesn't mean by more emotional or negative reactions, but by emulating what others have learned to do - acceptance (not accepting T but the reality of T in my life), positivity (I was very negative person before, hence my years of living with anxiety and panic disorders), patience (letting the body to have enough time to heal), strategies (CBT, mindfulness meditation, abdominal breathing), finding joy amid the pain (willing to peacefully co-exist with T and yet living life abundantly to compensate for any suffering from T).",
"@jacob21  I have been using the neuromodulator since February.",
"i have to really focus on my T for it to bother me...so id say its in between mild and severely mild most days, sometimes spikes to where i feel i need to mask it but i dont likeusing maskers since they seem to make it worse after i use them, i pray for everyone with T to find relieve from the contant noise no matter how severe or mild it is im praying for all you guys  it will get better",
"Trobalt makes a sedating effect on brain that erradicates any sing of stress and this indirectly also helps to lower the T level.",
"I took a couple oral prednisone  packs and it did nothing for me.",
"anyone try acupuncture",
"At the moment I am reading the LLLT thread to see if I can make my mind up.",
"I will keep posting to provide updates on MuteButton but my experience so far is that Neurmod are not out to sell this for the sake of it and are honest and diligent about who this device is sold to.",
"I am on fluoxetine, 20 mg every day since october.",
"Not enough to perforate it though, so she prescribed me Medrol.",
"Although the study I read stated that it was an epidural of lidocaine that worked.",
"So if before Trobalt i used to pee every 5 hours (yes big bladder), or 8h at night sleep, now im doing everey 7. well no big deal.",
"Keppra seems quite safe, as I've had no side-effects and steroids can cause a heck of a lot of issues, so why not try keppra?",
"Mirtazapine had the same effect on me as you.",
"One of the members on this forum ( @Goofy ) found a hyperbaric chamber run by a non-profit organization in Ohio with affordable fees.",
"Doctor's Best Extra Strength Ginkgo costs $6.72.",
"Regarding your TRT question, TRT never involves masking.",
"I went out, drank a lot, basically half a bottle of vodka, combined with 3 red bulls (lots of caffeine) and I slept like a baby without masking or anything.",
"The reason there is no cure for tinnitus has nothing to do with TRT and the such.",
"People it was the trobalt but he took it early onset.",
"I'm really excited  about your improvements in heairing threshold, that's why I also ordered this home laser.",
"Just wish my doctor hadn't tried the Zoloft on me, I was handling it all so much better before it caused mine to really spike.",
"While I am no fan of TRT in the first place, I at the same time have no doubt that the CHARITE TRT-clinic in Berlin is run according to the highest professional standards.",
"I'd be inclined to try out melatonin as its readily available in the pharmacies here.",
"Lexapro was prescribed.",
"The prednisone is also making it almost impossible for me to sleep, but I'm willing to cope with that if it means I can keep the peace of my ears mostly intact.",
"Sleep deprivation is one sure way to fire up T. Get some bed time masking such as a sound machine or a sound pillow etc., so you can fall asleep better.",
"(And the very last thing she needed was the TRT that she came to me for originally!)",
"She also told me that kind of super hearing is gone at 20 the latest and I am 26 so she thinks it's something else but I will give this a try it sure seems better than the soundcure.",
"Any other shared experiences using Melatonin would be appreciated.",
"I don't know if Trobalt did much (after one hour now).",
"How long were you taking Trobalt, how long have you been off it and has the VS subsided anything at all during this time?",
"I have read about Prednisone being taken for Menieres symptoms to and helps to calm them down.",
"@Pleasure_Paulie  how long did you try memantine?",
"TRT is a heap of dogshit.",
"Along the way, managed Tinnitus with sleep meds and masking (Trazodone & Lunesta).",
"Also, I have gotten off of Ginkgo Biloba for the past couple of weeks (I have ordered my second batch) since I have not received my new shipment.",
"So no masking with TV, car noise, music, etc.",
"I'm not recommending it, but looking through the thread some claimed it reduced their T even further while on trobalt.",
"I rather skip the Ginkgo if it seems it does not help and replace with <20mg of Niacin.",
"For the record, I do happen to take vit D3 and magnesium daily, and they don't seem to have any affect on my tinnitus.",
"I've personally had no side-effects from keppra and just drunkenness from trobalt.",
"I can't speak for everyone, but I suspect that if you put your masking track on, and then test yourself (can I still hear it?)",
"If it's not TMJ related, i might ask the ENT for Trobalt, but for some weird reason i just think he won't prescribe it to me..",
"If these larger clinical trials replicate efficacy of rTMS that has been demonstrated in the present study, then steps should be taken to implement the procedure as a clinical treatment for chronic tinnitus.",
"I'm thinking of doing that notched therapy but just don't know if it'll be money down the drain...",
"3) If you have computer and speakers, you can try these excellent masking sounds: TT's audio player: https://www.tinnitustalk.com/audioplayer/ or download free sound generator â€˜aire freshenerâ€™: http://www.peterhirschberg.com/mysoftware.html or make your own rain sound: http://mynoise.net/NoiseMachines/rainNoiseGenerator.php or search youtube with words like 'tinnitus masking sounds', 'white noise', 'rain sound' etc.",
"Cost: TRT trainers typically recommend that a professional sound-generating device similar to a hearing aid be worn 24/7.",
"There must be something to habituation as they are not all downing loads of Trobalt or Xanax (well maybe on the xanax thing but not as likely).",
"With that said, if we are concerned with helping the 9s and 10s now, why not recommend CBT, which has ostensibly a stronger current recommendation from Cochrane than TRT currently does?",
"and he referred me for CBT.",
"(Am101 only allows people who've had it no more than 3 months).",
"I have read that there is a 2 percent chance to get T from using Lexapro.",
"[Let's ignore acute tinnitus and AM-101, corticosteroids, etc.",
"Studies by Partheniadis-Stumpf, Wedel (placebo-controlled), Mirz, Nakashima, and Teggi separately concluded LLLT failed to treat tinnitus.",
"From my own experience about what you listed, I can say that I agree with you about the Lexapro.",
"Hi, Erik and Calin,   I used to take Natural Calm magnesium powder (magnesium citrate), but recently changed over to ALTA Health Products magnesium chloride tablets.",
"Tinn Man - Congratulations on completing 18 months of TRT!",
"It did charge me up a bit and sleep was an issue even with remeron and gabapentin.",
"Basically, AudioNotch is a simple interface for creating notched music/white noise files.",
"On the other hand, the anxiety is worse so a little masking comes in handy.",
"And if you are bound and determined to give LLLT a try (as seems to be the case), then if the cheaper device does not work, eventually you are going to shell out the additional money to try Dr. Wilden's device if not actually visit him in his clinic.",
"So a week or so ago I began an HBOT treatment that is roughly 4 times a week for what will eventually be 20 dives.",
"I think what people might be getting at is that if you don't have an opinion on how LLLT affects hearing, then it lessens the value of any thoughts you might have about LLLT for tinnitus."])
y_train_text = [["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neg","yes"],
["neg","yes"],
["neg","no"],
["pos","yes"],
["neu","no"],
["neu","no"],
["neu","no"],
["pos","yes"],
["neu","no"],
["neu","no"],
["neg","yes"],
["neg","yes"],
["pos","yes"],
["neg","yes"],
["neu","no"],
["neu","no"],
["neu","no"],
["pos","yes"],
["neu","yes"],
["pos","no"],
["neu","no"],
["neg","yes"],
["neu","no"],
["neu","yes"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neg","yes"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","yes"],
["pos","yes"],
["neu","no"],
["neg","yes"],
["neu","no"],
["neu","yes"],
["neg","yes"],
["neu","no"],
["neu","no"],
["neg","yes"],
["neu","yes"],
["pos","yes"],
["neg","yes"],
["neu","yes"],
["neg","yes"],
["neg","yes"],
["neu","yes"],
["neu","yes"],
["neu","no"],
["neu","no"],
["neu","yes"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["neu","no"],
["pos","yes"],
["neg","yes"],
["neg","yes"],
["neg","yes"],
["neu","yes"],
["pos","yes"],
["neu","no"],
["neg","yes"],
["neu","no"],
["pos","yes"],
["neu","no"],
["pos","yes"],
["neg","yes"]]

X_test = np.array(["Progress Report Progress Report Date:  Sep 11, 2014 Current Retigabine Dosage:  800mg a day Current Side Effects:  tiredness Current Tinnitus Severity:  1 out of 10 Changes in Tinnitus:  My tinnitus basically doesn't exist.",
"I had a big point around 7 years ago when I stopped in the street and I noticed that the ambient noise wasn't masking my tinnitus - in my mind I said this is it, I'm going to hear this over most ambient noise.",
"Ev Everything I've read about CBT is all about stress reduction and acceptance.",
"Coffee is out (this one was tough as hell) amped up my Zinc and Magnesium plus doing around 2ooomg of vit C per day.",
"Karen mentioned melatonin as a natural alternative.",
"If you google for neurontin tinnitus or gaba tinnitus, you'll find that there are people with tinnitus who've got neurontin for other conditions and it hasn't helped their tinnitus at all.",
"I would try to get into that AM-101 if you fit most of the criteria, don't be too quick to exclude yourself because you might think you have something like this causing your tinnitus, take every opportunity to get the best help you can get.",
"If it doesn't work then AM-101 is pretty much the only pharmaceutical option outside of off-label drugs like retigabine or keppra.",
"Are you trying anything else or are you going to try Trobalt again?",
"That's an interesting contrast with retigabine, which has so far appeared effective at higher doses spaced evenly throughout the day.",
"Thanks for all the info you have provided on LLLT.",
"Since oral and/or topical administration of NAC is feasible for long-term treatment in humans, and NAC has a good safety profile, it is reasonable to consider clinical trials to evaluate the effects of prolonged treatment with NAC in patients with RP.",
"As part of the on-going efforts of Team Trobalt, I learnt during the spring of 2015 that, yet another development was underway.",
"i am finding I think that the flixonase nasule drops are making a hissing noise in my right ear as it isn't there till i pop them in a few hours after taking the prednisolone.",
"Part of the interview includes an in-depth discussion of what TRT is and what TRT isn't.",
"I have never heard about NAC, so I will call my family doctor and ask if I can take it.",
"It is definitely either the ACRN or the massive amounts of NAC I've been taking.",
"Sadly, for me, neither Rozerem nor melatonin are a long-term solution.",
"I currently use magnesium glycinate, which really agrees with me.",
"That kind of feeling will subside as time goes by, especially if you adopt some helpful strategies, CBT, mindfulness, TRT, etc., etc.",
"So AUT000063 operates on a different group of potassium channels from Retigabine and there is nothing currently available which is comparable to AUT00063."])
target_names = ['Sentiment', 'Factuality']

mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(y_train_text)
print(mlb.fit_transform(y_train_text))
print(mlb.classes_)

classifier = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', RandomForestClassifier())])

classifier.fit(X_train, Y)
predicted = classifier.predict(X_test)
all_labels = mlb.inverse_transform(predicted)

for item, labels in zip(X_test, all_labels):
    print('{0} => {1}'.format(item, ', '.join(labels)))


